apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/maaanish/hello-kubernetes-dev-config/base/?ref=v1.0
patchesStrategicMerge:
  - custom-env.yaml
  - replica-count.yaml
